"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{if .Root}} ⚡ {{end}}{{.Folder | replace \"~\" \"🏠\"}} @ {{.HostName}}"
final_space = true
version = 2

[[blocks]]
type = "prompt"
alignment = "left"

[[blocks.segments]]
background = "#3498db"
foreground = "#FFFFFF"
leading_diamond = "\ue0b6"
style = "diamond"
template = " {{ .Icon }} "
trailing_diamond = "\ue0b0"
type = "os"

# [[blocks.segments]]
# background = "#16a085"
# foreground = "#ffffff"
# leading_diamond = "\ue0b6"
# style = "diamond"
# template = "\ueb99 {{ .UserName }}"
# trailing_diamond = "\ue0b0"
# type = "session"

# [[blocks.segments]]
# background = "#26BDBB"
# foreground = "#0C212F"
# leading_diamond = "<transparent,#26BDBB>\ue0b0</>"
# style = "diamond"
# template = " {{ .Path }} "
# trailing_diamond = "\ue0b0"
# type = "path"

# [blocks.segments.properties]
# folder_icon = "..."
# folder_separator_icon = "<transparent> \ue0b1 </>"
# home_icon = "\ueb06"
# style = "agnoster_short"

[[blocks.segments]]
background = "#ecf0f1"
foreground = "#0C212F"
powerline_symbol = "\ue0b0"
style = "powerline"
template = " {{ .Path }} "
type = "path"

[blocks.segments.properties]
folder_icon = "..."
#folder_separator_icon = "<transparent> \ue0b1 </>"
home_icon = "\ueb06"
#style = "agnoster_short"

[[blocks.segments]]
background = "#16a085"
background_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}#8e44ad{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#8e44ad{{ end }}",
    "{{ if gt .Ahead 0 }}#8e44ad{{ end }}",
    "{{ if gt .Behind 0 }}#8e44ad{{ end }}",
]
foreground = "#FFFFFF"
leading_diamond = "\ue0b6"
powerline_symbol = "\ue0b0"
style = "powerline"
template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "
trailing_diamond = "\ue0b4"
type = "git"

[blocks.segments.properties]
branch_max_length = 25
fetch_stash_count = true
fetch_status = true
fetch_upstream_icon = true

[[blocks.segments]]
background = "#FFD43B"
foreground = "#111111"
powerline_symbol = "\ue0b0"
style = "powerline"
template = "  {{ .Full }} "
#template = " \ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
type = "python"

[blocks.segments.properties]
display_mode = "context"
fetch_virtual_env = true
home_enabled=true
display_default=true
fetch_version=true

[[blocks.segments]]
background = "#2ecc71"
foreground = "#ffffff"
powerline_symbol = "\ue0b0"
style = "powerline"
template = " \ue718 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} "
type = "node"

[blocks.segments.properties]
fetch_version = true
display_mode="files"


[[blocks]]
type = "rprompt"
[[blocks.segments]]
background = "#0077c2"
foreground = "#ffffff"
style = "plain"
template = "<#0077c2,transparent>\ue0b6</> \uf489 {{ .Name }} <transparent,#0077c2>\ue0b2</>"
type = "shell"

[[blocks.segments]]
background = "#1BD760"
foreground = "#111111"
invert_powerline = true
powerline_symbol = "\ue0b2"
style = "powerline"
template = " \uf167 {{ .Icon }}{{ if ne .Status \"stopped\" }}{{ .Artist }} - {{ .Track }}{{ end }} "
type = "ytm"

[blocks.segments.properties]
paused_icon = "\uf04c "
playing_icon = "\uf04b "


# [[blocks.segments]]
# background = "#f36943"
# background_templates = [
#     "{{if eq \"Charging\" .State.String}}#40c4ff{{end}}",
#     "{{if eq \"Discharging\" .State.String}}#ff5722{{end}}",
#     "{{if eq \"Full\" .State.String}}#4caf50{{end}}",
# ]
# foreground = "#ffffff"
# invert_powerline = true
# powerline_symbol = "\ue0b2"
# style = "powerline"
# template = " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}\uf295 "
# type = "battery"

# [blocks.segments.properties]
# charged_icon = "\ue22f "
# charging_icon = "\ue234 "
# discharging_icon = "\ue231 "


[[blocks.segments]]
background = "#34495e"
foreground = "#ffffff"
invert_powerline = true
leading_diamond = "\ue0b2"
style = "diamond"
template = " {{ .CurrentDate | date .Format }} "
trailing_diamond = "\ue0b4"
type = "time"



#type = "os"
#style = "diamond"
#leading_diamond=
#background = "#000000"
#foreground = "#24EBE8"
